// import type { Candidato } from './types'

// export const dataExemple: Candidato[] = [
//   {
//     id: 1,
//     nome: 'Lucas',
//     email: 'jl.lucassantos098@gmail.com',
//     cnpjCpf: '078.371.893-45',
//     telefone: '(88) 99930-6514',
//     sexo: 'masculino',
//     especializacao: 'nao',
//     experiencia: 'nao',
//     experienciaHomeCare: 'nao',
//     cargo: 'Terapeuta Ocupacional',
//     valor: 33,
//     idade: 22,
//     cep: '63022-180',
//     cidade: 'Juazeiro do Norte',
//     estado: 'CE',
//     documentosValidados: false,
//     ativo: true,
//     atuacoes: [
//       {
//         id: 3,
//         cidade: {
//           id: 358,
//           idEstado: 6,
//           nome: 'Alto Santo',
//           codigoIbge: '230070',
//           createdAt: '2019-05-15T13:15:26.000Z',
//           updatedAt: '2019-05-15T13:15:26.000Z',
//           deletedAt: null,
//         },
//       },
//     ],
//   },
//   {
//     id: 2,
//     nome: 'Ana',
//     email: 'ana.santos@gmail.com',
//     cnpjCpf: '123.456.789-01',
//     telefone: '(88) 98888-1234',
//     sexo: 'feminino',
//     especializacao: 'sim',
//     experiencia: 'sim',
//     experienciaHomeCare: 'sim',
//     cargo: 'Fisioterapeuta',
//     valor: 50,
//     idade: 30,
//     cep: '62010-100',
//     cidade: 'Fortaleza',
//     estado: 'CE',
//     documentosValidados: true,
//     ativo: true,
//     atuacoes: [
//       {
//         id: 4,
//         cidade: {
//           id: 360,
//           idEstado: 6,
//           nome: 'Sobral',
//           codigoIbge: '230800',
//           createdAt: '2019-06-15T13:15:26.000Z',
//           updatedAt: '2019-06-15T13:15:26.000Z',
//           deletedAt: null,
//         },
//       },
//     ],
//   },
//   {
//     id: 3,
//     nome: 'Carlos',
//     email: 'carlos.martins@gmail.com',
//     cnpjCpf: '234.567.890-12',
//     telefone: '(88) 97777-4321',
//     sexo: 'masculino',
//     especializacao: 'sim',
//     experiencia: 'sim',
//     experienciaHomeCare: 'sim',
//     cargo: 'Enfermeiro',
//     valor: 40,
//     idade: 28,
//     cep: '62020-200',
//     cidade: 'Caucaia',
//     estado: 'CE',
//     documentosValidados: false,
//     ativo: true,
//     atuacoes: [
//       {
//         id: 5,
//         cidade: {
//           id: 361,
//           idEstado: 6,
//           nome: 'Maracanaú',
//           codigoIbge: '230570',
//           createdAt: '2019-07-20T13:15:26.000Z',
//           updatedAt: '2019-07-20T13:15:26.000Z',
//           deletedAt: null,
//         },
//       },
//     ],
//   },
//   {
//     id: 4,
//     nome: 'Fernanda',
//     email: 'fernanda.rodrigues@gmail.com',
//     cnpjCpf: '345.678.901-23',
//     telefone: '(88) 96666-8765',
//     sexo: 'feminino',
//     especializacao: 'sim',
//     experiencia: 'sim',
//     experienciaHomeCare: 'sim',
//     cargo: 'Psicóloga',
//     valor: 45,
//     idade: 32,
//     cep: '63030-300',
//     cidade: 'Crato',
//     estado: 'CE',
//     documentosValidados: true,
//     ativo: true,
//     atuacoes: [
//       {
//         id: 6,
//         cidade: {
//           id: 362,
//           idEstado: 6,
//           nome: 'Iguatu',
//           codigoIbge: '230390',
//           createdAt: '2019-08-25T13:15:26.000Z',
//           updatedAt: '2019-08-25T13:15:26.000Z',
//           deletedAt: null,
//         },
//       },
//     ],
//   },
//   {
//     id: 5,
//     nome: 'João',
//     email: 'joao.silva@gmail.com',
//     cnpjCpf: '456.789.012-34',
//     telefone: '(88) 95555-2345',
//     sexo: 'masculino',
//     especializacao: 'nao',
//     experiencia: 'nao',
//     experienciaHomeCare: 'nao',
//     cargo: 'Médico',
//     valor: 60,
//     idade: 35,
//     cep: '62040-400',
//     cidade: 'Aquiraz',
//     estado: 'CE',
//     documentosValidados: true,
//     ativo: true,
//     atuacoes: [
//       {
//         id: 7,
//         cidade: {
//           id: 363,
//           idEstado: 6,
//           nome: 'Beberibe',
//           codigoIbge: '230130',
//           createdAt: '2019-09-30T13:15:26.000Z',
//           updatedAt: '2019-09-30T13:15:26.000Z',
//           deletedAt: null,
//         },
//       },
//     ],
//   },
//   {
//     id: 6,
//     nome: 'Sergio',
//     email: 'joao.silva@gmail.com',
//     cnpjCpf: '456.789.012-34',
//     telefone: '(88) 95555-2345',
//     sexo: 'masculino',
//     especializacao: 'nao',
//     experiencia: 'nao',
//     experienciaHomeCare: 'nao',
//     cargo: 'Médico',
//     valor: 60,
//     idade: 35,
//     cep: '62040-400',
//     cidade: 'Aquiraz',
//     estado: 'CE',
//     documentosValidados: true,
//     ativo: true,
//     atuacoes: [
//       {
//         id: 7,
//         cidade: {
//           id: 363,
//           idEstado: 6,
//           nome: 'Beberibe',
//           codigoIbge: '230130',
//           createdAt: '2019-09-30T13:15:26.000Z',
//           updatedAt: '2019-09-30T13:15:26.000Z',
//           deletedAt: null,
//         },
//       },
//     ],
//   },
//   {
//     id: 7,
//     nome: 'Mario',
//     email: 'joao.silva@gmail.com',
//     cnpjCpf: '456.789.012-34',
//     telefone: '(88) 95555-2345',
//     sexo: 'masculino',
//     especializacao: 'nao',
//     experiencia: 'nao',
//     experienciaHomeCare: 'nao',
//     cargo: 'Médico',
//     valor: 60,
//     idade: 35,
//     cep: '62040-400',
//     cidade: 'Aquiraz',
//     estado: 'CE',
//     documentosValidados: true,
//     ativo: true,
//     atuacoes: [
//       {
//         id: 7,
//         cidade: {
//           id: 363,
//           idEstado: 6,
//           nome: 'Beberibe',
//           codigoIbge: '230130',
//           createdAt: '2019-09-30T13:15:26.000Z',
//           updatedAt: '2019-09-30T13:15:26.000Z',
//           deletedAt: null,
//         },
//       },
//     ],
//   },
// ]
